-- AlterTable
ALTER TABLE "Applicant" ADD COLUMN IF NOT EXISTS "preferredLocation" TEXT NOT NULL DEFAULT '';
ALTER TABLE "Applicant" ADD COLUMN IF NOT EXISTS "assignedScheduleId" TEXT;
ALTER TABLE "Applicant" ALTER COLUMN "dateOfBirth" DROP NOT NULL;
ALTER TABLE "Applicant" ALTER COLUMN "email" SET DEFAULT '';
ALTER TABLE "Applicant" ALTER COLUMN "examCenter" DROP NOT NULL;
ALTER TABLE "Applicant" ALTER COLUMN "examDate" DROP NOT NULL;
ALTER TABLE "Applicant" ALTER COLUMN "examTime" DROP NOT NULL;
ALTER TABLE "Applicant" ALTER COLUMN "status" SET DEFAULT 'WAITING_FOR_SLOT';
